name: Publish library

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          npm ci
          npm run build --if-present
      - name: Archive library artifacts
        uses: actions/upload-artifact@v2
        with:
          name: library
          path: |
            dist/ngx-material-spinner

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: library
      - shell: bash
        run: ls -la
      #- uses: actions/setup-node@v1
      #  with:
      #    node-version: 12
      #    registry-url: https://registry.npmjs.org/
      #- run: npm ci
      #- run: npm publish
      #  env:
      #    NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: library
      - shell: bash
        run: ls -la
      #- uses: actions/setup-node@v1
      #  with:
      #    node-version: 12
      #    registry-url: https://npm.pkg.github.com/
      #- run: npm ci
      #- run: npm publish
      #  env:
      #    NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
